# ==================================================================
# FORGE - DATABASE MODELS (AUTOGENERATED)
# ==================================================================

from app.models.base import Base
from app.models.catalog import (
    Attribute,
    BuffType,
    ForgeConfig,
    ForgeTierRecipe,
    VisualTier,
)
from app.models.player import PlayerAttribute, PlayerInventory, PlayerProfile, User
from app.models.artifact import Artifact, ForgeHistory
from app.models.prestige import PlayerBuff, PrestigeHistory
from app.models.activity import ActivityLog
from app.models.mission import Mission
from app.models.relic import Relic

# Import all models
__all__ = [
    "Base",
    "Attribute",
    "BuffType",
    "ForgeConfig",
    "ForgeTierRecipe",
    "VisualTier",
    "User",
    "PlayerProfile",
    "PlayerAttribute",
    "PlayerInventory",
    "Artifact",
    "ForgeHistory",
    "PrestigeHistory",
    "PlayerBuff",
    "ActivityLog",
    "Mission",
    "Relic",
]
